matrix:
  url: 'http://localhost:8448'
  as_token: 'as_token'
  hs_token: 'hs_token'
  master_user_id: '@_xmpp_master:localhost'
  prefix: '_xmpp_'

database:
  username: mjjb
  password: mjjb
  url: jdbc:postgresql://localhost/mjjb
  properties:
    charSet: UTF-8
